os: linux
dist: trusty
language: php
addons:
  apt:
    packages:
      - libmemcached-dev
      - cyrus-sasl-devel

php:
  - 7.1
  - 7.2
  - master

env:
#  - MEMCACHED_VERSION="2.0.0"
#  - MEMCACHED_VERSION="2.2.0"
  - MEMCACHED_VERSION="3.0.0"
  - MEMCACHED_VERSION="3.0.4"


sudo: false
notifications:
  email: false

before_install:
#  - configure --disable-memcached-sasl
  - echo "" | pecl install -f memcached-$MEMCACHED_VERSION

install:
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml --testdox

after_success:
  - bash <(curl -s https://codecov.io/bash)
